# Project

## Setup

Please download the raw data [here](project_files/raw_data.zip). 

These samples are from a study looking at the effect of a prebiotic on the gut microbiota of children with type 1 diabetes. To invesigate this, the researchers took samples at three timepoints (baseline, 3 months, and 6 months) and sequenced the **V3-V4** region of the 16S rRNA gene. 

## Task 1

The first step with all sequence data is to ensure the primers have been removed. The two most common tools to accomplish this are **Cutadapt** and **Trimmomatic**. 

Note: both of these tools can be used for quality trimming as well as primer removal but here we will perform the quality trimming in dada2 instead. 

### Cutadapt

You can find the documentation for this tool [here](https://cutadapt.readthedocs.io/en/stable/).

These are the parameters that contain the primer sequences:

- `-g : forward primer`
- `-G : reverse primer`
- `-a : reverse primer, reverse complement`
- `-A : forward primer, reverse complement` 

For this dataset, these are the appropriate primers:

```
-g TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG
-G GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
-a GGATTAGATACCCBDGTAGTCCTGTCTCTTATACACATCTCCGAGCCCACGAGAC
-A CTGCWGCCNCCCGTAGGCTGTCTCTTATACACATCTGACGCTGCCGACGA
```

Here is an example of how to execute Cutadapt from the command line:

```
cutadapt -g <sequence> -G <sequence> -a <sequence> -A <sequence> -o output_forward.fastq -p output_reverse.fastq input_forward.fastq input_reverse.fastq
```

### Trimmomatic

You can find the documentation for this tool [here](http://www.usadellab.org/cms/?page=trimmomatic). 

Instead of specifying forward and reverse reads, Trimmomatic takes a fasta file as input and searches the reads for all sequences in the files. When using Trimmomatic on paired-end reads, you will get four output files: forward and reverse reads that are still paired (reads for which both forward and reverse were kept) and forward and reverse reads that are unpaired. In general, the number of unpaired reads should be small and you can continue with your analysis without these.

For this dataset, you can use [this fasta](https://www.dropbox.com/s/wc2kihxfep23ycw/v3v4primers.fa?dl=0).

Here is an example of how to execute Trimmomatic from the command line:

```
java -jar trimmomatic-0.39.jar PE input_forward.fq.gz input_reverse.fq.gz output_forward_paired.fq.gz output_forward_unpaired.fq.gz output_reverse_paired.fq.gz output_reverse_unpaired.fq.gz ILLUMINACLIP:v3v4primers.fa:2:30:10:2:keepBothReads LEADING:0 TRAILING:0 MINLEN:0
```

## Task 2

Use the dada2 pipeline to generate a table of ASVs and a taxonomy table. 

1. Read the names of the fastq files into R and create a list of sample names.
2. Plot quality profiles of the raw reads for all samples. Save these as pdf files.
3. Filter and trim the data and generate the quality plots again. Save these as well.
4. Learn the error rates and visually inspect the estimated error rates.
5. Infer samples. 
6. Merge paired reads.
7. Construct sequence table.
8. Remove chimeras.
9. Track reads through the pipeline and ensure that no step of the analysis removed a large/unreasonable proportion of the reads.
10. Assign taxonomy using the Silva databse. 
11. Save the ASV table and taxonomy table using the `saveRDS()` function. 

## Task 3

Use the phyloseq package to generate do some basic analysis. For this section you will need the [metadata](https://www.dropbox.com/s/htomvrgruy7am7a/project_metadata.txt?dl=0).

1. Generate a histogram of the number of reads per sample. Does this look okay?
2. Generate a table of alpha diversity measures (Shannon, Simspon, and Chao1) and use this table to plot alpha diversity by treatment and timepoint.
3. Transform the data to relative abundances and remove ASVs that are only present in less than 5% of the samples. 
4. Perform a principal component analysis (PCoA) using the `ordinate()` function and `distance = "bray"`. Plot beta diversity.
5. Explore the composition of each sample by generating bar plots of the relative abundances at the level of phylum, family, and genus. For family and genus, plot only the top 10 most abundant taxa. 



